# @formatter:off
quarkus.http.port=${PORT:8081}
quarkus.http.test-port=${TEST_PORT:8083}
quarkus.http.test-ssl-port=${TEST_SSL_PORT:8446}
quarkus.http.host=0.0.0.0
quarkus.http.cors=true

# quarkus.http.cors.origins=*

quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH
quarkus.http.cors.headers=Accept,Origin,Authorization,Content-Type,X-Requested-With

quarkus.banner.path=banner

quarkus.native.add-all-charsets=true
quarkus.native.resources.includes=template/**
quarkus.native.enabled=true



quarkus.datasource.db-kind=postgresql

%local.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:assist-control}?currentSchema=${DB_SCHEMA:public}
%local.quarkus.datasource.username=${DB_USER:postgres}
%develop.quarkus.datasource.jdbc.url=jdbc:postgresql://mesadinero2-dev.cluster-cy5rvtfr1tpj.us-east-1.rds.amazonaws.com:5432/assist-control?currentSchema=public
%develop.quarkus.datasource.username=postgres
%staging.quarkus.datasource.jdbc.url=jdbc:postgresql://mesadinero2-dev.cluster-cy5rvtfr1tpj.us-east-1.rds.amazonaws.com:5432/assist-control?currentSchema=public
%staging.quarkus.datasource.username=postgres
%production.quarkus.datasource.jdbc.url=jdbc:postgresql://mesadinero2-dev.cluster-cy5rvtfr1tpj.us-east-1.rds.amazonaws.com:5432/assist-control?currentSchema=public
%production.quarkus.datasource.username=postgres
quarkus.datasource.password=${DB_PASS}

quarkus.mybatis.xmlconfig.enable=true
quarkus.mybatis.xmlconfig.path=mybatis-config.xml
quarkus.mybatis.mapper-locations=mapper

quarkus.swagger-ui.always-include=true

%local.log.curl.enabled=true
%develop.log.curl.enabled=true
%staging.log.curl.enabled=true
%production.log.curl.enabled=true
log.curl.header.authorization.enabled=false
